version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r tests/requirements.txt
            tox